 version: "3.7"
 services:
      apiServer:
          image: apiserver:latest
          ports:
          - 5000:5000
          links:
          - mysql
          command: ["node","server.js"]

      adminPortal:
          image: adminportal:latest
          ports:
          - 3001:3001
          links:
          - apiServer
          command: ["npm","start"]

      userPortal:
          image: userportal:latest
          ports:
          - 3000:3000
          links:
          - apiServer
          command: ["npm","start"]

      mysql:
          image: mysql:latest
          ports:
          - 3306:3306
          volumes:
              - ./config/db.sql:/docker-entrypoint-initdb.d/db.sql
          environment:
              MYSQL_ROOT_PASSWORD: root
              MYSQL_DATABASE: db
              MYSQL_USER: yassine
              MYSQL_PASSWORD: root

      phpmyadmin:
          image: phpmyadmin/phpmyadmin
          links: 
              - mysql
          ports:
              - 8080:80
          environment:
              PMA_HOST: mysql
              PMA_PORT: 3306
              PMA_ARBITRARY: 1
          restart: always